Remove triage/waiting-for-ci after PR is merge
quarkusio/quarkus-github-bot pull request #46
Opened 2021-03-19 16:20 UTC by SaumyaSingh1

Hi @FroMage @gsmet :) 

This is the PR for #29

2021-03-19 17:51 UTC, gsmet requested changes
Hey Saumya,

The logic looks good. I added some comments to improve it.

One thing though: we try to keep each rule self contained so that we can easily tweak/drop one without breaking another.

So the idea would be to create your own `RemoveWaitingForCiLabelWhenMerged` class.

Once this is done, next step would be to add a test. The test framework is a bit tricky so maybe let's discuss it together once the first iteration is in.

2021-03-19 17:51 UTC, gsmet commented on src/main/java/io/quarkus/bot/MarkClosedPullRequestInvalid.java
> +            if (!pullRequest.getLabels().isEmpty()) {
You can drop that test given the other advices below (as the log will be inside the logic, you won't need this anymore).

2021-03-19 17:51 UTC, gsmet commented on src/main/java/io/quarkus/bot/MarkClosedPullRequestInvalid.java
> +                if (!quarkusBotConfig.isDryRun()) {
This test should be around line 33 and you should log the action only if it does something so the LOG.info() line will be inside the if of line 32.

2021-03-19 17:51 UTC, gsmet commented on src/main/java/io/quarkus/bot/MarkClosedPullRequestInvalid.java
> +                            pullRequest.removeLabels(Labels.TRIAGE_WAITING_FOR_CI);
You can `break;` from the for loop as soon as you removed it as you won't find a second one (labels are unique).

2021-03-19 17:52 UTC, gsmet commented
Better check the comments on the Files changed page, they will make more sense with all the logic visible: https://github.com/quarkusio/quarkus-bot/pull/46/files .

2021-03-22 02:29 UTC, SaumyaSingh1 commented
> One thing though: we try to keep each rule self contained so that we can easily tweak/drop one without breaking another.
> So the idea would be to create your own `RemoveWaitingForCiLabelWhenMerged` class.
> 
Yes, I created a separate class `RemoveWaitingForCiLabelWhenMerged`, and added the logic of this rule there. 

> Once this is done, next step would be to add a test. The test framework is a bit tricky so maybe let's discuss it together once the first iteration is in.

okay, sure :)

2021-03-22 16:00 UTC, gsmet approved these changes
I made a small adjustment because in the end I think we can remove the label for every closed PR (even if not merged). It might happen that the label is added and in the end the PR doesn't pass CI and we close it as invalid. My fault, I hadn't thought of that when I created the issue. I just removed a if so that's no biggie.

I also added a formatter config to the project. So now, when you do mvn clean install, it will format the code with our conventions (typically 4 spaces for indentation instead of 3).

2021-03-22 16:00 UTC, merged

2021-03-22 16:00 UTC, gsmet commented
And merged, thanks!